package agent

import (
	"crypto/rand"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// DefaultStateDir matches the systemd unit's StateDirectory=almanaut-agent.
const DefaultStateDir = "/var/lib/almanaut-agent"

const agentIDFile = "agent-id"

// uuidv4Pattern validates the shape of a UUIDv4: 8-4-4-4-12 hex with version
// nibble 4 and RFC 4122 variant nibble (8-b). The validator and generator both
// use this pattern so they cannot drift apart.
var uuidv4Pattern = regexp.MustCompile(`^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`)

// LoadOrCreateAgentID returns the agent's persistent identity, generating and
// storing one on first run.
//
// The id is generated here rather than taken from /etc/machine-id on purpose:
// machine-id is regenerated by cloud-init and some provisioning tools, and is
// empty on first boot of several images. An inventory key that can change
// underneath produces duplicate host records, so the agent owns the id and
// therefore owns its lifecycle.
func LoadOrCreateAgentID(dir string) (string, error) {
	path := filepath.Join(dir, agentIDFile)
	switch raw, err := os.ReadFile(path); {
	case err == nil:
		if id := strings.TrimSpace(string(raw)); id != "" && isValidUUIDv4(id) {
			return id, nil
		}
		// An empty file, whitespace-only file, or malformed content is corruption —
		// fall through and write a fresh one rather than reporting invalid or
		// truncated id forever (which would create duplicate hosts on the server).
	case !os.IsNotExist(err):
		return "", fmt.Errorf("read agent id: %w", err)
	}
	return writeNewAgentID(dir)
}

// ResetAgentID discards the stored identity and writes a new one. This is what
// an operator runs on a cloned VM whose copied state file made the server
// answer 409.
func ResetAgentID(dir string) (string, error) { return writeNewAgentID(dir) }

func writeNewAgentID(dir string) (string, error) {
	id, err := newUUIDv4()
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", fmt.Errorf("create state dir: %w", err)
	}
	path := filepath.Join(dir, agentIDFile)
	tmpPath := path + ".tmp"
	if err := os.WriteFile(tmpPath, []byte(id+"\n"), 0o600); err != nil {
		return "", fmt.Errorf("write agent id: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		_ = os.Remove(tmpPath) // best effort cleanup
		return "", fmt.Errorf("rename agent id: %w", err)
	}
	return id, nil
}

// isValidUUIDv4 checks that a string has the shape of a UUIDv4: 8-4-4-4-12 hex
// with version nibble 4 and RFC 4122 variant nibble (8-b).
func isValidUUIDv4(s string) bool {
	return uuidv4Pattern.MatchString(s)
}

// newUUIDv4 builds a random UUID from crypto/rand. A dependency for 12 lines
// would not earn its place in a binary this small.
func newUUIDv4() (string, error) {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", fmt.Errorf("generate agent id: %w", err)
	}
	b[6] = (b[6] & 0x0f) | 0x40 // version 4
	b[8] = (b[8] & 0x3f) | 0x80 // RFC 4122 variant
	return fmt.Sprintf("%x-%x-%x-%x-%x", b[0:4], b[4:6], b[6:8], b[8:10], b[10:16]), nil
}
