-- On-host inventory agent ingest. The agent<->host binding lives in its own
-- table rather than as columns on hosts: last_seen changes on every report, and
-- as a hosts column it would enter domain.Host and therefore domain.Diff,
-- writing a changelog entry per host per hour. Keeping it here means only real
-- field changes reach the change history.
CREATE TABLE host_agents (
    host_id     INTEGER PRIMARY KEY REFERENCES hosts(id) ON DELETE CASCADE,
    agent_id    TEXT    NOT NULL UNIQUE,  -- UUID generated by the agent on first run
    fingerprint TEXT    NOT NULL,         -- hostname + sorted MACs; used for clone detection
    last_seen   TEXT    NOT NULL          -- RFC3339 UTC
);

-- Full report payloads, kept as history like discovery_runs (not a catalog
-- entity). Rich data (disks, interfaces, kernel, uptime) is displayed, never
-- filtered on, so it stays JSON instead of becoming flat host columns.
CREATE TABLE agent_reports (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    host_id        INTEGER NOT NULL REFERENCES hosts(id) ON DELETE CASCADE,
    agent_id       TEXT    NOT NULL,
    received_at    TEXT    NOT NULL,      -- RFC3339 UTC
    agent_version  TEXT    NOT NULL,
    schema_version INTEGER NOT NULL,
    payload        TEXT    NOT NULL       -- the raw report JSON
);
CREATE INDEX idx_agent_reports_host ON agent_reports (host_id, id DESC);
